Update README.md
IBM-Cloud/vpc-api-samples pull request #2
Opened 2019-06-26 18:45 UTC by keith-merchant-ibm

2019-06-26 18:54 UTC, astha-jain requested changes

2019-06-26 18:54 UTC, astha-jain commented on README.md
> +This repository consists of a variety of code snippets intended to aid developer interaction with resources belonging to VPC on classic laaS Offering. This repository is intended to be used for docum
It should be `VPC on Classic IaaS offering` as it is the name of offering.

2019-06-26 18:54 UTC, astha-jain commented on README.md
> +The the example below shows how to retrieve a token, list all VPCs, and create a VPC.
here.

2019-06-26 21:29 UTC, keith-merchant-ibm commented on README.md
> +This repository consists of a variety of code snippets intended to aid developer interaction with resources belonging to VPC on classic laaS Offering. This repository is intended to be used for docum
Corrected

2019-06-26 21:30 UTC, keith-merchant-ibm commented on README.md
> +The the example below shows how to retrieve a token, list all VPCs, and create a VPC.
Corrected

2019-06-27 04:56 UTC, astha-jain approved these changes
Looks good 👍

2019-06-27 17:25 UTC, merged